<?php

return [
    'previous_tax_year' => [
        'default' => '১৯৭০-১৯৭১',
        'list' => [
            '১৯৭০-১৯৭১' => '১৯৭০-১৯৭১',
            '১৯৭১-১৯৭২' => '১৯৭১-১৯৭২',
            '১৯৭২-১৯৭৩' => '১৯৭২-১৯৭৩',
            '১৯৭৩-১৯৭৪' => '১৯৭৩-১৯৭৪',
            '১৯৭৪-১৯৭৫' => '১৯৭৪-১৯৭৫',
            '১৯৭৫-১৯৭৬' => '১৯৭৫-১৯৭৬',
            '১৯৭৬-১৯৭৭' => '১৯৭৬-১৯৭৭',
            '১৯৭৭-১৯৭৮' => '১৯৭৭-১৯৭৮',
            '১৯৭৮-১৯৭৯' => '১৯৭৮-১৯৭৯',
            '১৯৭৯-১৯৮০' => '১৯৭৯-১৯৮০',
            '১৯৮০-১৯৮১' => '১৯৮০-১৯৮১',
            '১৯৮১-১৯৮২' => '১৯৮১-১৯৮২',
            '১৯৮২-১৯৮৩' => '১৯৮২-১৯৮৩',
            '১৯৮৩-১৯৮৪' => '১৯৮৩-১৯৮৪',
            '১৯৮৪-১৯৮৫' => '১৯৮৪-১৯৮৫',
            '১৯৮৫-১৯৮৬' => '১৯৮৫-১৯৮৬',
            '১৯৮৬-১৯৮৭' => '১৯৮৬-১৯৮৭',
            '১৯৮৭-১৯৮৮' => '১৯৮৭-১৯৮৮',
            '১৯৮৮-১৯৮৯' => '১৯৮৮-১৯৮৯',
            '১৯৮৯-১৯৯০' => '১৯৮৯-১৯৯০',
            '১৯৯০-১৯৯১' => '১৯৯০-১৯৯১',
            '১৯৯১-১৯৯২' => '১৯৯১-১৯৯২',
            '১৯৯২-১৯৯৩' => '১৯৯২-১৯৯৩',
            '১৯৯৩-১৯৯৪' => '১৯৯৩-১৯৯৪',
            '১৯৯৪-১৯৯৫' => '১৯৯৪-১৯৯৫',
            '১৯৯৫-১৯৯৬' => '১৯৯৫-১৯৯৬',
            '১৯৯৬-১৯৯৭' => '১৯৯৬-১৯৯৭',
            '১৯৯৭-১৯৯৮' => '১৯৯৭-১৯৯৮',
            '১৯৯৮-১৯৯৯' => '১৯৯৮-১৯৯৯',
            '১৯৯৯-২০০০' => '১৯৯৯-২০০০',
            '২০০০-২০০১' => '২০০০-২০০১',
            '২০০১-২০০২' => '২০০১-২০০২',
            '২০০২-২০০৩' => '২০০২-২০০৩',
            '২০০৩-২০০৪' => '২০০৩-২০০৪',
            '২০০৪-২০০৫' => '২০০৪-২০০৫',
            '২০০৫-২০০৬' => '২০০৫-২০০৬',
            '২০০৬-২০০৭' => '২০০৬-২০০৭',
            '২০০৭-২০০৮' => '২০০৭-২০০৮',
            '২০০৮-২০০৯' => '২০০৮-২০০৯',
            '২০০৯-২০১০' => '২০০৯-২০১০',
            '২০১০-২০১১' => '২০১০-২০১১',
            '২০১১-২০১২' => '২০১১-২০১২',
            '২০১২-২০১৩' => '২০১২-২০১৩',
            '২০১৩-২০১৪' => '২০১৩-২০১৪',
            '২০১৪-২০১৫' => '২০১৪-২০১৫',
            '২০১৫-২০১৬' => '২০১৫-২০১৬',
            '২০১৬-২০১৭' => '২০১৬-২০১৭',
            '২০১৭-২০১৮' => '২০১৭-২০১৮',
            '২০১৮-২০১৯' => '২০১৮-২০১৯',
            '২০১৯-২০২০' => '২০১৯-২০২০',
            '২০২০-২০২১' => '২০২০-২০২১',
            '২০২১-২০২২' => '২০২১-২০২২',
            '২০২২-২০২৩' => '২০২২-২০২৩',
        ]
    ],
    'taxpayer_types' => [
        '1' => 'কোম্পানি',
        '2' => 'কোম্পানি ব্যতিত',
    ],
    'actions' => [
        '1' => 'বকেয়া পরিশোধের জন্য তাগাদাপত্র',
        '2' => 'আপীলে বিচারাধীন',
        '3' => 'ট্রাইব্যুনালে বিচারাধীন',
        '4' => 'হাইকোর্ট/সুপ্রিমকোর্টে বিচারাধীন',
        '5' => '১৪৩ ধারায় ব্যাংক জব্দ',
        '6' => 'সার্টিফিকেট মামলা দায়েরকৃত',
        '7' => 'ADR দায়েরকৃত',
        '8' => '১২১এ ধারায় রিভিশন দায়েরকৃত',
        '9' => 'অন্যান্য',
    ],

    'disputed_actions' => [2, 3, 4, 7, 8],

    'universities' => [
        "Ahsanullah University of Science and Technology",
        "American International University Bangladesh",
        "Army University of Engineering and Technology (BAUET), Qadirabad",
        "Army University of Science and Technology(BAUST), Saidpur ",
        "ASA University Bangladesh",
        "Asian University for Women",
        "Asian University of Bangladesh",
        "Atish Dipankar University of Science and Technology",
        "Bangabandhu Sheikh Mujib Medical University",
        "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
        "Bangabandhu Sheikh Mujibur Rahman Maritime University",
        "Bangabandhu Sheikh Mujibur Rahman Science & Technology University",
        "Bangladesh Agricultural University",
        "Bangladesh Army International University of Science & Technology, Cumilla",
        "Bangladesh Islami University",
        "Bangladesh Open University",
        "Bangladesh Textile University",
        "Bangladesh University",
        "Bangladesh University of Business & Technology (BUBT)",
        "Bangladesh University of Engineering & Technology",
        "Bangladesh University of Health Sciences",
        "Bangladesh University of Health Sciences",
        "Bangladesh University of Professionals",
        "Barisal University",
        "Begum Rokeya University",
        "BGMEA University of Fashion & Technology",
        "BRAC University",
        "Britannia University",
        "Canadian University of Bangladesh",
        "CCN University of Science & Technology",
        "Central University of Science and Technology",
        "Central Women's University",
        "Chittagong Independent University (CIU)",
        "Chittagong University of Engineering & Technology",
        "Chittagong Veterinary and Animal Sciences University",
        "City University",
        "Cumilla University",
        "Coxs Bazar International University",
        "Daffodil International University",
        "Dhaka International University",
        "Dhaka University of Engineering & Technology",
        "East Delta University , Chittagong",
        "East West University",
        "Eastern University",
        "European University of Bangladesh",
        "Exim Bank Agricultural University, Bangladesh",
        "Fareast International University",
        "Feni University",
        "First Capital University of Bangladesh",
        "German University Bangladesh",
        "Global University Bangladesh",
        "Gono Bishwabidyalay",
        "Green University of Bangladesh",
        "Hajee Mohammad Danesh Science & Technology University",
        "Hamdard University Bangladesh",
        "Independent University, Bangladesh",
        "International Islamic University, Chittagong",
        "International University of Business Agriculture & Technology",
        "Ishakha International University",
        "Islamic Arabia University",
        "Islamic University",
        "Islamic University of Technology, Gazipur",
        "Jagannath University",
        "Jahangirnagar University",
        "Jatiya Kabi Kazi Nazrul Islam University",
        "Jessore University of Science & Technology",
        "Khulna University",
        "Khulna University of Engineering and Technology",
        "Khwaja Yunus Ali University ",
        "Leading University, Sylhet",
        "Manarat International University",
        "Mawlana Bhashani Science & Technology University",
        "Metropolitan University, Sylhet",
        "N.P.I University of Bangladesh",
        "National University",
        "Noakhali Science & Technology University",
        "Northern University, Bangladesh",
        "North Bengal International University",
        "North East University Bangladesh",
        "North South University",
        "North Western University, Khulna",
        "Northern University of Business & Technology, Khulna",
        "Notre Dame University Bangladesh",
        "Pabna University of Science and Technology",
        "Patuakhali Science And Technology University",
        "Port City International University",
        "Premier University, Chittagong",
        "Presidency University",
        "Primeasia University",
        "Prime University",
        "Pundro University of Science & Technology ",
        "Rabindra Moitri University, Kushtia",
        "Rajshahi Science & Technology University (RSTU), Natore",
        "Rajshahi University of Engineering & Technology",
        "Ranada Prasad Shaha University",
        "Rangamati Science and Technology University",
        "Royal University of Dhaka",
        "Shahjalal University of Science & Technology",
        "Shanto Mariam University of Creative Technology",
        "Sheikh Fazilatunnesa Mujib University",
        "Sher-e-Bangla Agricultural University",
        "Sonargaon University",
        "South Asian University",
        "Southeast University",
        "Stamford University, Bangladesh",
        "State University Of Bangladesh",
        "Sylhet Agricultural University",
        "Sylhet International University, Sylhet",
        "The International University of Scholars",
        "The Millennium University",
        "The People's University of Bangladesh",
        "University of Asia Pacific",
        "Times University Bangladesh",
        "United International University",
        "University of Chittagong/Chittagong University",
        "University of Creative Technology, Chitagong",
        "University of Development Alternative",
        "University of Dhaka/Dhaka University",
        "University of Information Technology & Sciences",
        "University of Liberal Arts Bangladesh",
        "University of Rajshahi/Rajshahi University",
        "University of Science & Technology, Chittagong",
        "University of South Asia",
        "Uttara University",
        "Varendra University",
        "Victoria University of Bangladesh",
        "World University of Bangladesh",
        "Z.H Sikder University of Science & Technology",
        "Foreign University (equivalence approved)",
        "BGC Trust University Bangladesh",
        "Southern University Bangladesh"
    ],


];
